import React, { useMemo, useState } from 'react';
const TRENDS=[['Cherry Red','Color',96],['Soft Tailoring','Silhouette',93],['Washed Denim','Fabric',91],['Sheer Layering','Detail',88],['Quiet Utility','Aesthetic',86],['Metallic Accents','Detail',82]];
const FABRICS={cotton:['Breathable, soft','Spring / Summer','Machine wash, low heat',78],linen:['Cool, textured','Spring / Summer','Gentle wash, air dry',90],denim:['Structured, durable','All season','Cold wash, air dry',72],silk:['Fluid, premium','All season','Dry clean / gentle wash',64],wool:['Warm, insulating','Autumn / Winter','Dry clean / hand wash',84],recycled:['Technical, lightweight','All season','Cold wash',88]};
const STYLES=['Minimal','Streetwear','Luxury','Smart Casual','Resort','Avant-Garde']; const OCCASIONS=['Everyday','Office','Party','Travel','Wedding','Date Night'];
const api=async(url,body)=>{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw Error(d?.error?.message||'Request failed');return d};
const scoreDesign=t=>({Creativity:62+t.length%37,Trend:68+t.length%29,Wearability:70+t.length%25,Commercial:64+t.length%31});
const download=(name,text)=>{const u=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)};
export default function FeatureHub(){
 const [open,setOpen]=useState(false),[tab,setTab]=useState('outfit'),[prompt,setPrompt]=useState('premium black oversized jacket with utility details'),[style,setStyle]=useState('Minimal'),[occasion,setOccasion]=useState('Everyday'),[fabric,setFabric]=useState('linen'),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[error,setError]=useState('');
 const [versions,setVersions]=useState(()=>{try{return JSON.parse(localStorage.getItem('fashion_versions')||'[]')}catch{return[]}}); const score=useMemo(()=>scoreDesign(prompt),[prompt]);
 const run=async(fn)=>{setBusy(true);setError('');setResult(null);try{setResult(await fn())}catch(e){setError(e.message)}finally{setBusy(false)}};
 const image=p=>api('/api/design',{prompt:p}).then(d=>d.image); const ai=p=>api('/api/gemini',{prompt:p}).then(d=>d.specification);
 const tabs=[['outfit','👗','Outfit AI'],['palette','🎨','Palette'],['variations','✨','Variations'],['copilot','🧠','Copilot'],['trends','📈','Trend Radar'],['fabric','🧵','Fabric'],['sketch','✏️','Sketch → Design'],['collection','🧥','Collection'],['score','🏆','Score'],['techpack','📐','Tech Pack'],['versions','🕘','Versions'],['share','🔗','Share']];
 const outfit=()=>run(()=>image(`complete ${occasion} ${style} fashion outfit based on ${prompt}, coordinated top bottom shoes accessories, editorial studio photography`));
 const variations=()=>run(async()=>{const a=[];for(const v of ['color','silhouette','fabric','premium detail'])a.push(await image(`${prompt}, ${v} variation, professional fashion product photography`));return a});
 const copilot=()=>run(()=>ai(`Act as a professional fashion design copilot. Analyze: ${prompt}. Return concise advice for fit, fabric, colors, construction, styling, target customer and commercial improvements.`));
 const sketch=()=>run(()=>image(`polished realistic fashion product concept from this sketch description: ${prompt}, accurate construction, front three-quarter studio view`));
 const collection=()=>run(()=>image(`six-piece coordinated fashion collection based on ${prompt}, ${style} aesthetic, editorial lookbook`));
 const save=()=>{const v={id:Date.now(),prompt,style,occasion,score,createdAt:new Date().toLocaleString()};const n=[...versions,v];setVersions(n);localStorage.setItem('fashion_versions',JSON.stringify(n));setResult('Version saved.')};
 const share=async()=>{const text=`AI Fashion Studio\n${prompt}\nStyle: ${style}\nOccasion: ${occasion}`;if(navigator.share)await navigator.share({title:'AI Fashion Design',text});else{await navigator.clipboard?.writeText(text);setResult('Design summary copied.')}};
 const tech=()=>{download('ai-fashion-tech-pack.txt',`AI FASHION STUDIO — TECH PACK\n\nDesign: ${prompt}\nStyle: ${style}\nOccasion: ${occasion}\nFabric: ${fabric}\nSustainability: ${FABRICS[fabric][3]}/100\n\nFIT\nConfirm final measurements before production.\n\nCONSTRUCTION\nReinforced seams; clean finishing; production sample required.\n\nQUALITY\nCheck stitch consistency, measurement tolerance, fabric defects and colorfastness.`);setResult('Tech Pack exported.')};
 if(!open)return <button onClick={()=>setOpen(true)} style={{position:'fixed',right:22,bottom:22,zIndex:9998,border:0,borderRadius:999,padding:'14px 18px',background:'#111',color:'#fff',boxShadow:'0 12px 40px #0008',fontWeight:800,cursor:'pointer'}}>✦ Feature Lab</button>;
 return <div style={S.overlay}><div style={S.shell}><aside style={S.side}><b style={{fontSize:18}}>AI Fashion Lab</b><small style={{display:'block',color:'#777',margin:'4px 0 18px'}}>Advanced creative workspace</small>{tabs.map(([id,ic,n])=><button key={id} onClick={()=>{setTab(id);setResult(null);setError('')}} style={{...S.nav,background:tab===id?'#292929':'transparent',color:tab===id?'#fff':'#999'}}>{ic} {n}</button>)}<button onClick={()=>setOpen(false)} style={{...S.nav,marginTop:16,border:'1px solid #333'}}>Close</button></aside><main style={S.main}><h1>{tabs.find(x=>x[0]===tab)?.[2]}</h1><p style={{color:'#777'}}>Build, evaluate and export fashion concepts.</p>{['outfit','variations','copilot','sketch','collection'].includes(tab)&&<textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={4} style={S.input}/>} {(tab==='outfit'||tab==='collection')&&<div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{STYLES.map(x=><button key={x} onClick={()=>setStyle(x)} style={{...S.pill,background:style===x?'#fff':'#171717',color:style===x?'#000':'#aaa'}}>{x}</button>)}{OCCASIONS.map(x=><button key={x} onClick={()=>setOccasion(x)} style={{...S.pill,background:occasion===x?'#fff':'#171717',color:occasion===x?'#000':'#aaa'}}>{x}</button>)}</div>}
 {tab==='outfit'&&<Action text="Generate complete outfit" onClick={outfit}/>} {tab==='variations'&&<Action text="Generate 4 variations" onClick={variations}/>} {tab==='copilot'&&<Action text="Ask Fashion AI Copilot" onClick={copilot}/>} {tab==='sketch'&&<><p style={{color:'#999'}}>Describe the sketch here, then generate a polished concept.</p><Action text="Convert to design" onClick={sketch}/></>} {tab==='collection'&&<Action text="Generate 6-piece collection" onClick={collection}/>} {tab==='palette'&&<Palette/>} {tab==='trends'&&<Trend/>} {tab==='fabric'&&<Fabric fabric={fabric} setFabric={setFabric}/>} {tab==='score'&&<Score score={score}/>} {tab==='techpack'&&<><Card text="Production starter pack: fit, material, construction and QC. Always validate measurements with your manufacturer."/><Action text="Export Tech Pack" onClick={tech}/></>} {tab==='versions'&&<Versions versions={versions} onSave={save}/>} {tab==='share'&&<><Card text="Share the current design summary using the browser share sheet or clipboard."/><Action text="Share / Copy" onClick={share}/></>}
 {busy&&<Card text="Processing with AI…"/>}{error&&<div style={{...S.card,color:'#ffaaaa',borderColor:'#633'}}>{error}</div>}{result&&<Result value={result}/>}</main></div></div>;
}
const Action=({text,onClick})=><button onClick={onClick} style={S.action}>{text} →</button>;const Card=({text})=><div style={S.card}>{text}</div>;
function Result({value}){if(typeof value==='string')return <Card text={value}/>;if(Array.isArray(value))return <div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:12}}>{value.map((x,i)=><img key={i} src={x} alt={`variation ${i+1}`} style={{width:'100%',borderRadius:14}}/>)}</div>;return <pre style={{whiteSpace:'pre-wrap',background:'#171717',padding:16,borderRadius:14,color:'#ddd'}}>{JSON.stringify(value,null,2)}</pre>}
function Palette(){return <div><Card text="Premium starter palette — use as a direction, then validate under your intended lighting and material."/><div style={{display:'flex',gap:10,marginTop:14}}>{['#111111','#F5F1E8','#A61B29','#304D3A','#D8B08C','#6C5B7B'].map(c=><div key={c} style={{width:80,height:60,borderRadius:10,background:c,border:'1px solid #444'}} title={c}/>)}</div></div>}
function Trend(){return <div style={{display:'grid',gap:8}}>{TRENDS.map(t=><div key={t[0]} style={S.row}><b>{t[0]}</b><span>{t[1]}</span><strong>{t[2]}</strong></div>)}</div>}
function Fabric({fabric,setFabric}){const f=FABRICS[fabric];return <div><select value={fabric} onChange={e=>setFabric(e.target.value)} style={S.select}>{Object.keys(FABRICS).map(x=><option key={x}>{x}</option>)}</select><Card text={`${f[0]}. Best for ${f[1]}. Care: ${f[2]}. Sustainability: ${f[3]}/100.`}/></div>}
function Score({score}){return <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:10}}>{Object.entries(score).map(([k,v])=><div key={k} style={S.card}><small style={{color:'#777'}}>{k}</small><div style={{fontSize:30,fontWeight:900}}>{v}</div></div>)}</div>}
function Versions({versions,onSave}){return <div><Action text="Save current version" onClick={onSave}/><div style={{display:'grid',gap:8,marginTop:14}}>{versions.length?<>{versions.slice().reverse().map((v,i)=><div key={v.id} style={S.card}><b>Version {versions.length-i}</b><div style={{color:'#aaa'}}>{v.prompt}</div><small style={{color:'#666'}}>{v.createdAt}</small></div>)}</>:<Card text="No versions saved yet."/>}</div></div>}
const S={overlay:{position:'fixed',inset:0,zIndex:9999,background:'#050505ee',display:'flex',alignItems:'center',justifyContent:'center',padding:18},shell:{width:'min(1180px,100%)',height:'min(850px,94vh)',background:'#101010',border:'1px solid #292929',borderRadius:24,color:'#fff',display:'flex',overflow:'hidden',boxShadow:'0 30px 100px #000'},side:{width:220,borderRight:'1px solid #292929',padding:18,overflowY:'auto',flexShrink:0},nav:{width:'100%',textAlign:'left',padding:'10px 11px',marginBottom:5,border:0,borderRadius:10,cursor:'pointer'},main:{flex:1,overflowY:'auto',padding:28},input:{width:'100%',boxSizing:'border-box',background:'#171717',border:'1px solid #333',borderRadius:14,color:'#fff',padding:15,resize:'vertical'},pill:{padding:'8px 12px',borderRadius:999,border:'1px solid #333'},action:{padding:'13px 18px',border:0,borderRadius:12,background:'#fff',color:'#000',fontWeight:900,cursor:'pointer'},card:{padding:16,border:'1px solid #2c2c2c',borderRadius:14,color:'#aaa',lineHeight:1.6,marginTop:12},row:{display:'grid',gridTemplateColumns:'1fr 120px 50px',gap:10,padding:14,background:'#171717',borderRadius:12},select:{padding:12,borderRadius:10,background:'#171717',color:'#fff',border:'1px solid #333',marginBottom:12}};
