import React, { useEffect, useMemo, useState } from 'react';

const WINNERS = [
[1952,'Armi Kuusela','Finland'],[1953,'Christiane Martel','France'],[1954,'Miriam Stevenson','United States'],[1955,'Hillevi Rombin','Sweden'],[1956,'Carol Morris','United States'],[1957,'Gladys Zender','Peru'],[1958,'Luz Marina Zuluaga','Colombia'],[1959,'Akiko Kojima','Japan'],[1960,'Linda Bement','United States'],[1961,'Marlene Schmidt','Germany'],[1962,'Norma Nolan','Argentina'],[1963,'Iêda Maria Vargas','Brazil'],[1964,'Corinna Tsopei','Greece'],[1965,'Apasra Hongsakula','Thailand'],[1966,'Margareta Arvidsson','Sweden'],[1967,'Sylvia Hitchcock','United States'],[1968,'Martha Vasconcellos','Brazil'],[1969,'Gloria Diaz','Philippines'],[1970,'Marisol Malaret','Puerto Rico'],[1971,'Georgina Rizk','Lebanon'],[1972,'Kerry Anne Wells','Australia'],[1973,'Margarita Moran','Philippines'],[1974,'Amparo Muñoz','Spain'],[1975,'Anne Marie Pohtamo','Finland'],[1976,'Rina Messinger','Israel'],[1977,'Janelle Commissiong','Trinidad and Tobago'],[1978,'Margaret Gardiner','South Africa'],[1979,'Maritza Sayalero','Venezuela'],[1980,'Shawn Weatherly','United States'],[1981,'Irene Sáez','Venezuela'],[1982,'Karen Dianne Baldwin','Canada'],[1983,'Lorraine Downes','New Zealand'],[1984,'Yvonne Ryding','Sweden'],[1985,'Deborah Carthy-Deu','Puerto Rico'],[1986,'Bárbara Palacios','Venezuela'],[1987,'Cecilia Bolocco','Chile'],[1988,'Porntip Nakhirunkanok','Thailand'],[1989,'Angela Visser','Netherlands'],[1990,'Mona Grudt','Norway'],[1991,'Lupita Jones','Mexico'],[1992,'Michelle McLean','Namibia'],[1993,'Dayanara Torres','Puerto Rico'],[1994,'Sushmita Sen','India'],[1995,'Chelsi Smith','United States'],[1996,'Alicia Machado','Venezuela'],[1997,'Brook Lee','United States'],[1998,'Wendy Fitzwilliam','Trinidad and Tobago'],[1999,'Mpule Kwelagobe','Botswana'],[2000,'Lara Dutta','India'],[2001,'Denise Quiñones','Puerto Rico'],[2002,'Justine Pasek','Panama'],[2002,'Oxana Fedorova','Russia'],[2003,'Amelia Vega','Dominican Republic'],[2004,'Jennifer Hawkins','Australia'],[2005,'Natalie Glebova','Canada'],[2006,'Zuleyka Rivera','Puerto Rico'],[2007,'Riyo Mori','Japan'],[2008,'Dayana Mendoza','Venezuela'],[2009,'Stefanía Fernández','Venezuela'],[2010,'Ximena Navarrete','Mexico'],[2011,'Leila Lopes','Angola'],[2012,'Olivia Culpo','United States'],[2013,'Gabriela Isler','Venezuela'],[2014,'Paulina Vega','Colombia'],[2015,'Pia Wurtzbach','Philippines'],[2016,'Iris Mittenaere','France'],[2017,'Demi-Leigh Nel-Peters','South Africa'],[2018,'Catriona Gray','Philippines'],[2019,'Zozibini Tunzi','South Africa'],[2020,'Andrea Meza','Mexico'],[2021,'Harnaaz Sandhu','India'],[2022,"R'Bonney Gabriel",'United States'],[2023,'Sheynnis Palacios','Nicaragua'],[2024,'Victoria Kjær Theilvig','Denmark'],[2025,'Fátima Bosch','Mexico']
].map(([year,name,country]) => ({ year, name, country }));

const API='https://en.wikipedia.org/w/api.php?action=query&format=json&origin=*&prop=pageimages&piprop=thumbnail&pithumbsize=600&titles=';

export default function MissUniverseGallery(){
  const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[decade,setDecade]=useState('All'),[images,setImages]=useState({}),[loading,setLoading]=useState(false);
  const decades=['All','1950s','1960s','1970s','1980s','1990s','2000s','2010s','2020s'];
  const filtered=useMemo(()=>WINNERS.filter(w=>!query||`${w.name} ${w.country} ${w.year}`.toLowerCase().includes(query.toLowerCase())).filter(w=>decade==='All'||`${Math.floor(w.year/10)*10}s`===decade),[query,decade]);
  useEffect(()=>{let cancelled=false;const load=async()=>{setLoading(true);const next={};for(let i=0;i<WINNERS.length;i+=25){const batch=WINNERS.slice(i,i+25);try{const r=await fetch(API+batch.map(w=>encodeURIComponent(w.name)).join('|'));const d=await r.json();Object.values(d.query?.pages||{}).forEach(p=>{if(p.thumbnail?.source)next[p.title]=p.thumbnail.source});}catch{}if(cancelled)return;}setImages(next);setLoading(false)};load();return()=>{cancelled=true}},[]);
  if(!open)return <button onClick={()=>setOpen(true)} style={S.launch}>👑 Miss Universe Legacy</button>;
  return <div style={S.overlay}><section style={S.panel}><header style={S.header}><div><div style={S.eyebrow}>AI FASHION STUDIO</div><h1 style={S.title}>Miss Universe Legacy</h1><p style={S.sub}>Titleholders gallery · 1952–2025 · {WINNERS.length} records</p></div><button onClick={()=>setOpen(false)} style={S.close}>×</button></header><div style={S.tools}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search winner or country…" style={S.input}/><select value={decade} onChange={e=>setDecade(e.target.value)} style={S.select}>{decades.map(d=><option key={d}>{d}</option>)}</select></div>{loading&&<div style={S.notice}>Loading titleholder portraits from Wikipedia…</div>}<div style={S.grid}>{filtered.map(w=><article key={`${w.year}-${w.name}`} style={S.card}>{images[w.name]?<img src={images[w.name]} loading="lazy" alt={`${w.name} — Miss Universe ${w.year}`} style={S.img}/>:<div style={S.placeholder}>👑</div>}<div style={S.meta}><strong>{w.name}</strong><span>{w.country}</span><small>{w.year}</small></div></article>)}</div><footer style={S.footer}>Images are fetched at runtime from Wikipedia/Wikimedia sources. Source images remain subject to their respective licenses. The 2002 entries preserve the titleholder history (Justine Pasek and Oxana Fedorova).</footer></section></div>;
}

const S={overlay:{position:'fixed',inset:0,zIndex:10000,background:'#050505f5',padding:18,overflowY:'auto'},panel:{maxWidth:1280,margin:'0 auto',background:'#0d0d0d',color:'#fff',border:'1px solid #292929',borderRadius:24,padding:24,boxShadow:'0 30px 100px #000'},header:{display:'flex',justifyContent:'space-between',gap:20,alignItems:'flex-start'},eyebrow:{fontSize:11,letterSpacing:3,color:'#aaa',fontWeight:800},title:{fontSize:'clamp(30px,5vw,56px)',margin:'6px 0',fontWeight:950},sub:{color:'#888',margin:0},close:{width:44,height:44,borderRadius:12,border:'1px solid #333',background:'#171717',color:'#fff',fontSize:28,cursor:'pointer'},tools:{display:'flex',gap:10,margin:'22px 0',flexWrap:'wrap'},input:{flex:1,minWidth:240,padding:13,borderRadius:12,border:'1px solid #333',background:'#171717',color:'#fff'},select:{padding:'13px 16px',borderRadius:12,border:'1px solid #333',background:'#171717',color:'#fff'},notice:{padding:12,borderRadius:12,background:'#151515',color:'#999',marginBottom:14},grid:{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(180px,1fr))',gap:14},card:{background:'#151515',border:'1px solid #292929',borderRadius:16,overflow:'hidden'},img:{width:'100%',height:250,objectFit:'cover',display:'block'},placeholder:{height:250,display:'grid',placeItems:'center',fontSize:48,background:'#1a1a1a'},meta:{padding:13,display:'grid',gap:4},metaSpan:{color:'#aaa'},footer:{marginTop:20,color:'#666',fontSize:12,lineHeight:1.5},launch:{position:'fixed',right:22,bottom:78,zIndex:9997,border:0,borderRadius:999,padding:'13px 17px',background:'#171717',color:'#fff',boxShadow:'0 12px 40px #0008',fontWeight:800,cursor:'pointer'}};
